# Digistpark development without the Arduino IDE
# Christopher M Poole <mail@christopherpoole.net>

DIGISPARK_DIR = ../../../

TARGET                 = main
#DIGISPARK_LIBS         = 
MCU                    = attiny85
F_CPU                  = 16000000L

include $(DIGISPARK_DIR)/Arduino.mk

